[package]
name = "wgpu_triangle"
version = "0.1.0"
edition = "2021"


[dependencies]
winit = "0.30"
env_logger = "0.11"
wgpu = "0.20"
pollster = "0.3"
bytemuck = { version = "1.12", features = ["derive"] }
glam = { version = "0.28", features = ["bytemuck"] }